// Generated by GitHub Copilot - Sep-28-2026
import { expect, test } from '@playwright/test'

const productSku = process.env.E2E_PRODUCT_SKU

test.describe('Amazon readiness workflow', () => {
  test.skip(!productSku, 'Set E2E_PRODUCT_SKU to an isolated test product before running.')

  /**
   * Completes the product workflow through the visible dashboard controls.
   */
  test('moves a product from draft to published', async ({ page }) => {
    await page.goto('/dashboard')

    const productCard = page.locator('[class*="card"]').filter({ hasText: productSku! }).first()
    await expect(productCard).toBeVisible({ timeout: 30_000 })
    await productCard.click()

    const detailPanel = page.locator('[class*="panel"]').filter({ hasText: productSku! }).first()
    await expect(detailPanel).toBeVisible()

    const startWorkflow = detailPanel.getByRole('button', {
      name: 'Start Amazon Readiness workflow',
    })
    if (await startWorkflow.isVisible().catch(() => false)) {
      await startWorkflow.click()
    }

    await expect(detailPanel).toContainText('Draft', { timeout: 30_000 })
    const fillMissingFields = detailPanel.getByRole('button', { name: 'Fill Missing Fields' })
    if (await fillMissingFields.isVisible().catch(() => false)) {
      await fillMissingFields.click()
      await expect(fillMissingFields).toBeHidden({ timeout: 30_000 })
    }

    const submitForAudit = detailPanel.getByRole('button', { name: 'Submit for Audit' })
    await expect(submitForAudit).toBeEnabled({ timeout: 30_000 })
    await submitForAudit.click()
    await expect(detailPanel).toContainText('Audit Pending', { timeout: 30_000 })

    await expect
      .poll(() => detailPanel.innerText(), { timeout: 180_000 })
      .toMatch(/Audit Passed|Human Review/)

    const humanReview = detailPanel.getByRole('button', { name: 'Override & Approve' })
    if (await humanReview.isVisible().catch(() => false)) {
      await humanReview.click()
    } else {
      await expect(detailPanel).toContainText('Audit Passed')
    }

    await expect(detailPanel).toContainText('Audit Passed', { timeout: 30_000 })
    await detailPanel.getByRole('button', { name: 'Generate Video' }).click()
    await expect(detailPanel).toContainText('Video Requested', { timeout: 30_000 })
    await expect(detailPanel).toContainText('Video Ready', { timeout: 180_000 })

    await detailPanel.getByRole('button', { name: 'Approve & Publish' }).click()
    await expect(detailPanel).toContainText('Published', { timeout: 30_000 })
  })
})
